name: Build-LaTeX

on:
  push:
    branches: [ main ]

jobs:
  build-tex:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: sources
          root_file: Document.tex
